// Example: try...catch
try {
  let x = y; // y is not defined
} catch (err) {
  console.log("Caught an error:", err.message);
}
